(function H9YL(){"use strict";const d=document;const H=Hyphenopoly;function empty(){return Object.create(null)}
function eachKey(obj,fn){Object.keys(obj).forEach(fn)}(function configFeat(){if(H.cacheFeatureTests&&sessionStorage.getItem("Hyphenopoly_Loader")){H.clientFeat=JSON.parse(sessionStorage.getItem("Hyphenopoly_Loader"))}else{H.clientFeat={"langs":empty(),"polyfill":!1,"wasm":null}}}());(function configPaths(){H.dfltPaths=Object.create({"maindir":"../Hyphenopoly/","patterndir":"../Hyphenopoly/patterns/"});if(H.paths){if(H.paths.patterndir){H.dfltPaths.patterndir=H.paths.patterndir}
if(H.paths.maindir){H.dfltPaths.maindir=H.paths.maindir}}}());(function configSetup(){if(H.setup){H.setup.selectors=H.setup.selectors||{".hyphenate":{}};if(H.setup.classnames){eachKey(H.setup.classnames,function cn2sel(cn){H.setup.selectors["."+cn]=H.setup.classnames[cn]});H.setup.classnames=null;delete H.setup.classnames}
H.setup.timeout=H.setup.timeout||1000;H.setup.hide=H.setup.hide||"all"}else{H.setup={"hide":"all","selectors":{".hyphenate":{}},"timeout":1000}}}());(function configRequire(){H.lcRequire=new Map();eachKey(H.require,function copyRequire(k){H.lcRequire.set(k.toLowerCase(),H.require[k])});if(H.fallbacks){H.lcFallbacks=new Map();eachKey(H.fallbacks,function copyFallbacks(k){H.lcFallbacks.set(k.toLowerCase(),H.fallbacks[k].toLowerCase())})}}());H.toggle=function toggle(state){if(state==="on"){const stylesNode=d.getElementById("H9Y_Styles");if(stylesNode){stylesNode.parentNode.removeChild(stylesNode)}}else{const vis=" {visibility: hidden !important}\n";const sc=d.createElement("style");sc.id="H9Y_Styles";switch(H.setup.hide){case "all":sc.innerHTML="html"+vis;break;case "element":eachKey(H.setup.selectors,function eachSelector(sel){sc.innerHTML+=sel+vis});break;case "text":eachKey(H.setup.selectors,function eachSelector(sel){sc.innerHTML+=sel+" {color: transparent !important}\n"});break;default:sc.innerHTML=""}
d.getElementsByTagName("head")[0].appendChild(sc)}};(function setupEvents(){const definedEvents=new Map();const deferred=[];const tempRegister=[];function define(name,defFunc,cancellable){definedEvents.set(name,{"cancellable":cancellable,"default":defFunc,"register":[]})}
define("timeout",function def(e){H.toggle("on");window.console.info("Hyphenopolys 'FOUHC'-prevention timed out after %dms",e.delay)},!1);define("error",function def(e){window.console.error(e.msg)},!0);define("contentLoaded",function def(e){deferred.push({"data":e,"name":"contentLoaded"})},!1);define("engineLoaded",function def(e){deferred.push({"data":e,"name":"engineLoaded"})},!1);define("hpbLoaded",function def(e){deferred.push({"data":e,"name":"hpbLoaded"})},!1);function dispatch(name,data){data=data||empty();let defaultPrevented=!1;definedEvents.get(name).register.forEach(function call(currentHandler){data.preventDefault=function preventDefault(){if(definedEvents.get(name).cancellable){defaultPrevented=!0}};currentHandler(data)});if(!defaultPrevented&&definedEvents.get(name).default){definedEvents.get(name).default(data)}}
function addListener(name,handler,defer){if(definedEvents.has(name)){definedEvents.get(name).register.push(handler)}else if(defer){tempRegister.push({"handler":handler,"name":name})}else{H.events.dispatch("error",{"msg":"unknown Event \""+name+"\" discarded"})}}
if(H.handleEvent){eachKey(H.handleEvent,function add(name){addListener(name,H.handleEvent[name],!0)})}
H.events=empty();H.events.deferred=deferred;H.events.tempRegister=tempRegister;H.events.dispatch=dispatch;H.events.define=define;H.events.addListener=addListener}());function featureTestWasm(){function runWasmTest(){if(typeof WebAssembly==="object"&&typeof WebAssembly.instantiate==="function"){const module=new WebAssembly.Module(Uint8Array.from([0,97,115,109,1,0,0,0,1,6,1,96,1,127,1,127,3,2,1,0,5,3,1,0,1,7,8,1,4,116,101,115,116,0,0,10,16,1,14,0,32,0,65,1,54,2,0,32,0,40,2,0,11]));if(WebAssembly.Module.prototype.isPrototypeOf(module)){const inst=new WebAssembly.Instance(module);return WebAssembly.Instance.prototype.isPrototypeOf(inst)&&(inst.exports.test(4)!==0)}}
return!1}
if(H.clientFeat.wasm===null){H.clientFeat.wasm=runWasmTest()}}
const scriptLoader=(function scriptLoader(){const loadedScripts=new Map();return function loadScript(path,filename){if(!loadedScripts.has(filename)){const script=d.createElement("script");loadedScripts.set(filename,!0);script.src=path+filename;if(filename==="hyphenEngine.asm.js"){script.addEventListener("load",function listener(){H.events.dispatch("engineLoaded",{"msg":"asm"})})}
d.head.appendChild(script)}}}());const loadedBins=new Map();function binLoader(path,fne,name,msg){function fetchBinary(p,f,n,m){if(!loadedBins.has(n)){loadedBins.set(n,!0);window.fetch(p+f).then(function resolve(response){if(response.ok){if(n==="hyphenEngine"){H.binaries.set(n,response.arrayBuffer().then(function getModule(buf){return new WebAssembly.Module(buf)}))}else{H.binaries.set(n,response.arrayBuffer())}
H.events.dispatch(m[0],{"msg":m[1]})}})}}
function requestBinary(p,f,n,m){if(!loadedBins.has(n)){loadedBins.set(n,!0);const xhr=new XMLHttpRequest();xhr.onload=function onload(){H.binaries.set(n,xhr.response);H.events.dispatch(m[0],{"msg":m[1]})};xhr.open("GET",p+f);xhr.responseType="arraybuffer";xhr.send()}}
if(H.clientFeat.wasm){fetchBinary(path,fne,name,msg)}else{requestBinary(path,fne,name,msg)}}
function allocateMemory(lang){const specVal=new Map([["de",55],["hu",207],["nb-no",92],["nl",41]]);const wasmPages=specVal.get(lang)||32;H.specMems=H.specMems||new Map();if(H.clientFeat.wasm){H.specMems.set(lang,new WebAssembly.Memory({"initial":wasmPages,"maximum":256}))}else{Math.log2=Math.log2||function polyfillLog2(x){return Math.log(x)*Math.LOG2E};const asmPages=(2<<Math.floor(Math.log2(wasmPages)))*65536;H.specMems.set(lang,new ArrayBuffer(asmPages))}}(function featureTestCSSHyphenation(){const tester=(function tester(){let fakeBody=null;const css=(function createCss(){const props=["visibility:hidden;","-moz-hyphens:auto;","-webkit-hyphens:auto;","-ms-hyphens:auto;","hyphens:auto;","width:48px;","font-size:12px;","line-height:12px;","border:none;","padding:0;","word-wrap:normal"];return props.join("")}());function create(lang){if(H.clientFeat.langs[lang]){return}
fakeBody=fakeBody||d.createElement("body");const testDiv=d.createElement("div");testDiv.lang=lang;testDiv.id=lang;testDiv.style.cssText=css;testDiv.appendChild(d.createTextNode(H.lcRequire.get(lang)));fakeBody.appendChild(testDiv)}
function append(target){if(fakeBody){target.appendChild(fakeBody);return fakeBody}
return null}
function clear(){if(fakeBody){fakeBody.parentNode.removeChild(fakeBody)}}
return{"append":append,"clear":clear,"create":create}}());function checkCSSHyphensSupport(elm){return(elm.style.hyphens==="auto"||elm.style.webkitHyphens==="auto"||elm.style.msHyphens==="auto"||elm.style["-moz-hyphens"]==="auto")}
function exposeHyphenateFunction(lang){H.hyphenators=H.hyphenators||empty();if(!H.hyphenators[lang]){if(window.Promise){H.hyphenators[lang]=new Promise(function pro(rs,rj){H.events.addListener("engineReady",function handler(e){if(e.msg===lang){rs(H.createHyphenator(e.msg))}},!0);H.events.addListener("error",function handler(e){if(e.key===lang||e.key==="hyphenEngine"){rj(e.msg)}},!0)})}else{H.hyphenators[lang]={"then":function(){H.events.dispatch("error",{"msg":"Promises not supported in this engine. Use a polyfill (e.g. https://github.com/taylorhakes/promise-polyfill)!"})}}}}}
function loadRessources(lang){let filename=lang+".hpb";if(H.lcFallbacks&&H.lcFallbacks.has(lang)){filename=H.lcFallbacks.get(lang)+".hpb"}
H.binaries=H.binaries||new Map();featureTestWasm();scriptLoader(H.dfltPaths.maindir,"Hyphenopoly.js");if(H.clientFeat.wasm){binLoader(H.dfltPaths.maindir,"hyphenEngine.wasm","hyphenEngine",["engineLoaded","wasm"])}else{scriptLoader(H.dfltPaths.maindir,"hyphenEngine.asm.js")}
binLoader(H.dfltPaths.patterndir,filename,lang,["hpbLoaded",lang]);allocateMemory(lang);exposeHyphenateFunction(lang)}
H.lcRequire.forEach(function eachReq(value,lang){if(value==="FORCEHYPHENOPOLY"){H.clientFeat.polyfill=!0;H.clientFeat.langs[lang]="H9Y";loadRessources(lang)}else if(H.clientFeat.langs[lang]&&H.clientFeat.langs[lang]==="H9Y"){loadRessources(lang)}else{tester.create(lang)}});const testContainer=tester.append(d.documentElement);if(testContainer!==null){H.lcRequire.forEach(function eachReq(value,lang){if(value!=="FORCEHYPHENOPOLY"){const el=d.getElementById(lang);if(checkCSSHyphensSupport(el)&&el.offsetHeight>12){H.clientFeat.langs[lang]="CSS"}else{H.clientFeat.polyfill=!0;H.clientFeat.langs[lang]="H9Y";loadRessources(lang)}}});tester.clear()}}());function handleDCL(){if(H.setup.hide.match(/^(element|text)$/)){H.toggle("off")}
H.events.dispatch("contentLoaded",{"msg":["contentLoaded"]})}
if(H.clientFeat.polyfill){if(H.setup.hide==="all"){H.toggle("off")}
if(H.setup.hide!=="none"){H.setup.timeOutHandler=window.setTimeout(function timedOut(){H.toggle("on");H.events.dispatch("timeout",{"delay":H.setup.timeout})},H.setup.timeout)}
if(d.readyState==="loading"){d.addEventListener("DOMContentLoaded",handleDCL,{"once":!0,"passive":!0})}else{handleDCL()}}else{window.Hyphenopoly=null}
if(H.cacheFeatureTests){sessionStorage.setItem("Hyphenopoly_Loader",JSON.stringify(H.clientFeat))}}())
